Support `condition` as a function
sindresorhus/p-if pull request #2
Opened 2016-10-22 19:55 UTC by sotojuan

Closes #1.

I just used `is-fn` to make the function act accordingly. If it looks good, I'll do the docs!

2016-10-22 19:59 UTC, sindresorhus requested changes

2016-10-22 19:59 UTC, sindresorhus commented on index.js
> +const isFn = require('is-fn');
From the `is-fn` readme:

> In Node.js, just use typeof fn which works exactly the same.

So really no point in this.

2016-10-22 19:59 UTC, sindresorhus commented on index.js
> +	if (isFn(cond)) {
It should be a function that can also return a promise that is awaited. See how I solved that here: https://github.com/sindresorhus/p-catch-if/blob/454fa343bbf147db4b00c0ba6fb2e103e997e570/index.js#L18-L20

Feel free to steal the tests from here too: https://github.com/sindresorhus/p-catch-if/blob/454fa343bbf147db4b00c0ba6fb2e103e997e570/test.js#L68-L89 (Needs to be adjusted though)

2016-10-22 19:59 UTC, sindresorhus commented on test.js
> +test('cond can be a function', async t => {
cond => condition

2016-10-22 20:16 UTC, sotojuan commented
All right, I *think* I got it. I kept the old tests for a regular function but I can remove those if needed. `cond` now works if it's a function that returns a Promise.

2016-10-22 20:24 UTC, sindresorhus commented on index.js
> +	return cond ? doIf(val) : (doElse ? doElse(val) : val);
This needs to test for `true` too.

You also have the same logic in two places now, which could be DRY'd up into a function.

2016-10-22 20:24 UTC, sindresorhus commented on package.json
> +  "dependencies": {}
Remove

2016-10-22 20:25 UTC, sindresorhus commented
> I kept the old tests for a regular function but I can remove those if needed. 

Keep 'em.

2016-10-22 20:25 UTC, sindresorhus commented
Readme needs to be updated.

2016-10-23 15:50 UTC, sotojuan commented
🐔

2016-10-27 03:13 UTC, sindresorhus commented
There are still some unresolved inline feedback.

2016-10-27 03:14 UTC, sindresorhus commented on readme.md
> +Type: `boolean` or `Function`
Drop the `or`

2016-10-27 03:14 UTC, sindresorhus commented on readme.md
> +Decides whether `doIf` or `doElse` is executed. Expected to return a `Promise` that resolves to `true` or the value `true`.
> Expected to return a `Promise` for `true` or the value `true`.

2016-10-30 17:29 UTC, sotojuan commented
Moved over the logic to its own function, but couldn't think of a good name for it. Let me know if I missed anything else 😎

2016-11-03 07:37 UTC, sindresorhus approved these changes

2016-11-03 07:38 UTC, merged

2016-11-03 07:38 UTC, sindresorhus commented
Looks great now. Thank you @sotojuan 🤘😎